name: Tests
on: [push]

jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install pytest

    - name: Test with pytest
      run: |
        pytest --exitfirst --verbose --failed-first